### PR TITLE
feat: add integration workflow

### PR DESCRIPTION
**Pull request by bournezjc**
# Summary
This PR adds a new integration workflow, triggered by either push, pull request or workflow dispatch.
# Test Plan
check Actions on github repository
image

image

### CODE REVIEW

**Comment by bap2pecs** [comment]
nice! could you also check why lint failed? when I run `make lint-go` locally it passes with no error

my golangci-lint version

```
$ golangci-lint --version                                                                                                                      [12:02:34]
golangci-lint has version 1.59.1 built with go1.22.4 from 1a55854 on 2024-06-08T22:05:49Z
```

**Comment by bournezjc** [comment]
I am able to reproduce the same err msg on my end. My lint version is
```
$ golangci-lint --version
golangci-lint has version 1.61.0 built with go1.23.1 from a1d6c560 on 2024-09-09T17:44:42Z
```

**Comment by bap2pecs** [comment]
ah ok. can u try to downgrade the version on CI?

the goal is we want to avoid modifying OP's code as much as possible

**Comment by bournezjc** [comment]
Downgraded to v1.59.1, looks good to me.
image

**Review by bap2pecs — APPROVED** [review]
Excited Hype - JJptubufblBJP3E3DK

**Pull request merged**
